#!/bin/bash

#  WorkingDirectory 	Will set the current working directory.
#  ExecStart 	Systemd will run this executable to start the service.
#  ExecStop 	Defines the way the service is stopped when systemctl stop is called on this service. Together with KillSignal, this value is responsible for a graceful shutdown.
#  KillSignal 	Is a very important value to determine how the ASP.NET Core web service is stopped. If the wrong value is used, the service is killed without gracefully shutting down it's services (e.g. BackgroundService, IHostedService, IDispose, etc).
#  KillMode 	Setting KillMode to process instead of control-group (default) allows to shutdown the main process and spawn new processes (e.g. for automatic update service).
#  SyslogIdentifier 	Primary identifier of this service. This name is used to run systemctl start/stop operations as well as to read the service log (journalctl).
#  Restart 	Ensure the service restarts after crashing. Takes one of no, on-success, on-failure, on-abnormal, on-watchdog, on-abort, or always.
#  RestartSec 	Amount of time to wait before restarting the service.

WHERE=$PWD

#cat < __EOF > /etc/systemd/system/weatherdisplay.api.service
cat << __EOF > temp.ok
[Unit]
Description=WeatherDisplay.Api
After=network-online.target firewalld.service
Wants=network-online.target

[Service]
Type=simple
WorkingDirectory=$PWD/WeatherDisplay.Api
ExecStart=sudo $HOME/.dotnet/dotnet $PWD/WeatherDisplay.Api/WeatherDisplay.Api.dll
ExecStop=/bin/kill $MAINPID
KillSignal=SIGTERM
KillMode=process
SyslogIdentifier=WeatherDisplay.Api
TimeoutStartSec=60
TimeoutStopSec=20

User=`whoami`
Group=`whoami`

Restart=no

Environment=ASPNETCORE_ENVIRONMENT=Production
Environment=DOTNET_PRINT_TELEMETRY_MESSAGE=false
Environment=DOTNET_ROOT=$HOME/.dotnet

[Install]
WantedBy=multi-user.target

__EOF

sudo apt update
sudo apt upgrade
sudo apt-get install -y libgdiplus

